service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  parseText:
    handler: handler.parseText
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript